# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  # adapter: mysql2
  # encoding: utf8mb4
  # collation: utf8mb4_general_ci
  # reconnect: true
  # pool: 3
  # username: root
  # password: 'Saa11!dfh4ffd9dsFjdflfed'
  # host: 0.0.0.0
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/bib-en-nrsv.SQLite3
  # database: db/bib-il-dhnt85.SQLite3
  # database: db/Dvor.dictionary.SQLite3 -- словарь Дворецкого (но в итоге использовали не его, а от Гурина .abs)
  # database: db/bib-il-dhnt85.SQLite3
  # database: db/bib-arab-avd.SQLite3
  # database: db/bib-ch-ccbs.SQLite3
  # database: db/bib-ge-sch51.SQLite3
  # database: db/bib-jap-new-interconf.SQLite3
  # database: db/GR-LXX-KOINE-Barach.SQLite3

# greek: LXX + Byz
# hebrew - OSM+ - это ленинградский кодекс, норм!
# eng - NKJV
# цся(ру) - elz
# ру - optina
# цся - elz?
# jp-ni - new interconfessional translation (новый межконфессиональный перевод). Вроде, католики сделали, один из наиболее нормальных из имеющихся переводов.
# ge-sch51 - женевское биб общество SCH 1951 Schlachter Genfer Bibelgesellschaft
# cn-ccbs - так до конца не разобрался чьё это, но Царство Божие хотя бы внутри, а не среди
# arab-avd - проверил ключевые места в этом и других переводах (jp, ge, cn, arab), они наиболее приемлемы по сравнению с остальными
# il - используется Ленингрдский кодекс OSB для ветхого завета и
#      лютеранский перевод нового завета bib-il-dhnt85
# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/elz.sqlite3
